-- ============================================
-- INVENTRO - FRASES BASE DO SISTEMA (INGLÊS)
-- Arquivo: 03-language-base.sql
-- Descrição: Frases em inglês para tradução
-- Execução: Automática via docker-entrypoint-initdb.d
-- ============================================

SET sql_mode = '';
SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;

USE inventro_db;

SELECT '========================================' AS '';
SELECT '🌐 Inserindo frases base...' AS 'Status';
SELECT '========================================' AS '';

-- --------------------------------------------------------
-- FRASES DO SISTEMA EM INGLÊS
-- --------------------------------------------------------

INSERT INTO `language` (`phrase`, `english`) VALUES
('login', 'Login'),
('email', 'Email Address'),
('password', 'Password'),
('reset', 'Reset'),
('dashboard', 'Dashboard'),
('home', 'Home'),
('profile', 'Profile'),
('profile_setting', 'Profile Setting'),
('firstname', 'First Name'),
('lastname', 'Last Name'),
('about', 'About'),
('preview', 'Preview'),
('image', 'Image'),
('save', 'Save'),
('upload_successfully', 'Upload Successfully!'),
('user_added_successfully', 'User Added Successfully!'),
('please_try_again', 'Please Try Again...'),
('inbox_message', 'Inbox Messages'),
('sent_message', 'Sent Message'),
('message_details', 'Message Details'),
('new_message', 'New Message'),
('receiver_name', 'Receiver Name'),
('sender_name', 'Sender Name'),
('subject', 'Subject'),
('message', 'Message'),
('message_sent', 'Message Sent!'),
('ip_address', 'IP Address'),
('last_login', 'Last Login'),
('last_logout', 'Last Logout'),
('status', 'Status'),
('delete_successfully', 'Delete Successfully!'),
('send', 'Send'),
('date', 'Date'),
('action', 'Action'),
('sl_no', 'SL No.'),
('are_you_sure', 'Are you sure?'),
('application_setting', 'Application Setting'),
('application_title', 'Application Title'),
('address', 'Address'),
('phone', 'Phone'),
('favicon', 'Favicon'),
('logo', 'Logo'),
('language', 'Language'),
('left_to_right', 'Left To Right'),
('right_to_left', 'Right To Left'),
('footer_text', 'Footer Text'),
('site_align', 'Application Alignment'),
('welcome_back', 'Welcome Back!'),
('please_contact_with_admin', 'Please Contact With Admin'),
('incorrect_email_or_password', 'Incorrect Email/Password'),
('select_option', 'Select Option'),
('hostname', 'Host Name'),
('username', 'User Name'),
('update_successfully', 'Update Successfully'),
('save_successfully', 'Saved Successfully!'),
('module_name', 'Module Name'),
('create', 'Create'),
('read', 'Read'),
('update', 'Update'),
('delete', 'Delete'),
('description', 'Description'),
('inactive', 'Inactive'),
('active', 'Active'),
('user_list', 'User List'),
('setting', 'Setting'),
('logout', 'Logout'),
('admin', 'Admin'),
('add_user', 'Add User'),
('user', 'User'),
('module', 'Module'),
('new', 'New'),
('inbox', 'Inbox'),
('sent', 'Sent'),
('download', 'Download'),
('inventory', 'Inventory'),
('account', 'Account'),
('customer', 'Customer'),
('expense', 'Expense'),
('hrm', 'HRM'),
('invoice', 'Invoice'),
('item', 'Item'),
('purchase', 'Purchase'),
('report', 'Report'),
('stock', 'Stock'),
('supplier', 'Supplier'),
('customer_list', 'Customer List'),
('customer_name', 'Customer Name'),
('mobile', 'Mobile'),
('add_new', 'Add New'),
('add', 'Add'),
('customer_update', 'Customer Update'),
('supplier_list', 'Supplier List'),
('supplier_name', 'Supplier Name'),
('supplier_add', 'Supplier Add'),
('supplier_edit', 'Supplier Edit'),
('previous_balance', 'Previous Balance'),
('department', 'Department'),
('designation', 'Designation'),
('add_employee', 'Add Employee'),
('manage_employee', 'Manage Employee'),
('department_name', 'Department name'),
('employee', 'Employee'),
('name', 'Name'),
('country', 'Country'),
('city', 'City'),
('zip', 'Zip'),
('salary', 'Salary'),
('amount', 'Amount'),
('attendance', 'Attendance'),
('in_time', 'In Time'),
('out_time', 'Out Time'),
('stay_time', 'Stay Time'),
('attendance_report', 'Attendance Report'),
('submit', 'Submit'),
('add_item', 'Add Item'),
('item_list', 'Item List'),
('unit', 'Unit'),
('category', 'Category'),
('new_purchase', 'New Purchase'),
('purchase_list', 'Purchase List'),
('add_invoice', 'Add Invoice'),
('invoice_list', 'Invoice List'),
('invoice_id', 'Invoice ID'),
('paid', 'Paid'),
('total_amount', 'Total Amount'),
('record_not_found', 'Record not found'),
('add_menu', 'Add Menu'),
('menu', 'Role Permission'),
('menu_list', 'Menu List'),
('add_role', 'Add Role'),
('role_list', 'Role List'),
('role_assign', 'User Assign Role'),
('assigned_userrole_list', 'Assigned List'),
('accounts', 'Accounts'),
('payment_or_receive', 'Payment or Receive'),
('manage_transaction', 'Manage Transaction'),
('payment', 'Payment'),
('receive', 'Receive'),
('bank', 'Bank'),
('add_bank', 'Add Bank'),
('bank_list', 'Bank List'),
('bank_name', 'Bank Name'),
('account_no', 'Account No'),
('branch_name', 'Branch Name'),
('salary_generat_list', 'Salary generate list'),
('salary_setup', 'Salary Setup'),
('purchase_date', 'Purchase Date'),
('chalan_no', 'Chalan No'),
('details', 'Details'),
('payment_type', 'Payment Type'),
('cash_payment', 'Cash Payment'),
('bank_payment', 'Bank Payment'),
('due_payment', 'Due Payment'),
('item_name', 'Item Name'),
('unit_qty', 'Unit Qty'),
('box_qty', 'Box Qty'),
('rate', 'Rate'),
('total', 'Total'),
('discount', 'Discount'),
('grand_total', 'Grand Total'),
('edit_purchase', 'Edit Purchase'),
('filter', 'Filter'),
('from_date', 'From Date'),
('to_date', 'To Date'),
('find', 'Find'),
('purchase_id', 'Purchase Id'),
('sl', 'Sl'),
('qty', 'Qty'),
('price', 'Price'),
('purchase_price', 'Purchase Price'),
('sale_price', 'Sale Price'),
('cartoon_qty', 'Cartoon Qty'),
('item_model', 'Item Model'),
('item_code', 'Item Code'),
('category_name', 'Category Name'),
('parent_category', 'Parent Category'),
('category_list', 'Category List'),
('add_category', 'Add Category'),
('unit_list', 'Unit List'),
('add_unit', 'Add Unit'),
('unit_name', 'Unit Name'),
('total_price', 'Total Price'),
('payment_amount', 'Payment Amount'),
('select_name', 'Select Name'),
('select_one', 'Select One'),
('receipt_amount', 'Receipt Amount'),
('isreceipt', 'Received/Payment'),
('supplier_ledger', 'Supplier Ledger'),
('total_credit', 'Total Credit'),
('total_debit', 'Total Debit'),
('balance', 'Balance'),
('stock_report_supplier_wise', 'Stock report (supplier wise)'),
('stock_report', 'Stock report'),
('purchase_report', 'Purchase Report'),
('stock_report_product_wise', 'Stock report product wise'),
('list', 'List'),
('generate', 'Generate'),
('month', 'Month'),
('by', 'By'),
('pay_now', 'Pay now'),
('receipt', 'Receipt'),
('close', 'Close'),
('note', 'Note'),
('account_adjustment', 'Account Adjustment'),
('payment_date', 'Payment Date'),
('bank_ledger', 'Bank Ledger'),
('ledger', 'Ledger'),
('transactionid', 'Transaction ID'),
('paid_amount', 'Paid Amount'),
('invoice_discount', 'Invoice Discount'),
('total_discount', 'Total Discount'),
('debit', 'Debit'),
('credit', 'Credit'),
('due', 'Due'),
('customer_ledger', 'Customer Ledger'),
('sales_report', 'Sales report'),
('sales', 'Sales'),
('invoice_details', 'Invoice Details'),
('bank_adjustment', 'Bank Adjustment'),
('currency_name', 'Currency Name'),
('currency', 'Currency'),
('cash', 'Cash'),
('cash_book', 'Cash book'),
('quantity', 'Quantity'),
('received_amount', 'Received Amount'),
('left', 'Left'),
('right', 'Right'),
('edit_phrase', 'Edit Phrase'),
('add_new_phrase', 'Add New Phrase'),
('add_language', 'Add Language'),
('add_language_name', 'Add Language Name'),
('add_phrase', 'Add Phrase'),
('phrase_name', 'Phrase Name'),
('phrase', 'Phrase'),
('about_me', 'About Me'),
('choose_file', 'Choose File'),
('more_info', 'More Info'),
('purchase_and_sales_report', 'Purchase and sales report'),
('cancel', 'Cancel'),
('menu_title', 'Menu Title'),
('page_url', 'Page URL'),
('parent_menu', 'Parent Menu'),
('role_name', 'Role Name'),
('select_deselect', 'Select/Deselect'),
('can_create', 'Can Create'),
('all', 'All'),
('can_read', 'Can Read'),
('can_edit', 'Can Edit'),
('can_delete', 'Can Delete'),
('user_name', 'User Name'),
('assigned_role', 'Assigned Role'),
('product_name', 'Product Name'),
('product_model', 'Product Model'),
('sales_price', 'Sales Price'),
('total_sales', 'Total Sales'),
('total_purchase', 'Total Purchase'),
('select_product', 'Select Product'),
('search', 'Search'),
('select_supplier', 'Select Supplier'),
('add_pos_invoice', 'Add POS Invoice'),
('return', 'Return'),
('payment_now', 'Pay Now'),
('supplier_return', 'Supplier Return'),
('customer_return', 'Customer Return'),
('sold_qty', 'Sold Qty'),
('return_qty', 'Return Qty'),
('reason', 'Reason'),
('deduction', 'Deduction'),
('customer_return_list', 'Customer Return List'),
('purchase_qty', 'Purchase Qty'),
('supplier_return_list', 'Supplier Return List'),
('cash_closing', 'Cash Closing'),
('last_closing_balance', 'Last Closing Balance'),
('closing_list', 'Closing List'),
('adjustment', 'Adjustment'),
('import_csv', 'Import CSV'),
('download_sample_file', 'Download sample file'),
('imported_successfully', 'Imported Successfully'),
('updated_successfully', 'Updated Successfully'),
('upload_csv_file', 'Upload csv file'),
('upload', 'Upload'),
('bank_book', 'Bank book'),
('deposit', 'Deposit'),
('withdraw', 'Withdraw'),
('stock_in', 'Stock In'),
('stock_out', 'Stock Out')
ON DUPLICATE KEY UPDATE english = VALUES(english);

SELECT '✅ Frases base inseridas!' AS 'Status';
